version: '3.8'
services:
  flask_app_db:
    build:
      context: ../challenge1
      dockerfile: Dockerfile
    container_name: flask_app_db
    ports:
      - "5001:5000" #port exposé sur l'hote:port dans le conteneur où flask écoute
    networks:
      - app_network
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/"

  flask_app_no_db:
    build:
      context: ../challenge1
      dockerfile: Dockerfile
    container_name: flask_app_no_db
    ports:
      - "5002:5000" #port exposé sur l'hote:port dans le conteneur où flask écoute
    networks:
      - app_network
    environment:
      NO_DB: "True"

  mongodb:
    image: mongo:6.0.20-rc3-jammy
    container_name: mongodb_server
    restart: always
    ports:
      - "27017:27017"
    environment: {}

    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

